{{ if .Values.app.secrets.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-backend.fullname" . }}-credentials
  labels:
    {{- include "api-backend.labels" . | nindent 4 }}
data:
  credentials.json: {{ .Values.app.secrets.credentials.value | b64enc | quote }}
{{- end }}