{{ if .Values.app.secrets.database.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-backend.fullname" . }}-database
  labels:
    {{- include "api-backend.labels" . | nindent 4 }}
data:
  OPENSEARCH_URL: {{ .Values.app.secrets.database.value | b64enc | quote }}
{{- end }}